package gui.Frames;

import Product.Product;
import Product.Wheels;
import gui.Panels.ProductPanel;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class ProductBrowse extends javax.swing.JFrame {

    private final ArrayList<javax.swing.JPanel> productPanels;

    /**
     * Creates new form ProductBrowse
     */
    public ProductBrowse() {
        this.productPanels = new ArrayList<>();
        initComponents();
    }

    public ProductBrowse(List<Product> Products) {
        this.productPanels = new ArrayList<>();
        for (Product product : Products) {
            this.productPanels.add(new ProductPanel(product));
        }
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductBrowse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        List<Product> prods = new ArrayList<>();
        prods.add(new Wheels(10, "ROAD", "RIM", "a", 1, 100.22f, "whel"));
        prods.add(new Wheels(10, "ROAD", "RIM", "a", 1, 100.22f, "whel"));
        prods.add(new Wheels(10, "ROAD", "RIM", "a", 1, 100.22f, "whel"));
        prods.add(new Wheels(10, "ROAD", "RIM", "a", 1, 100.22f, "whel"));

        java.awt.EventQueue.invokeLater(() -> new ProductBrowse(prods).setVisible(true));
    }

    public void clearProductPanels() {
        this.productPanels.clear();
    }

    private void selectWheelsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public void addProductPanel(Product product) {
        this.productPanels.add(new ProductPanel(product));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JPanel productBrowseMain = new JPanel();
        JPanel orderNav = new JPanel();
        JButton selectWheels = new JButton();
        JButton selectFrameSets = new JButton();
        JButton selectHandlebars = new JButton();
        JButton viewOrder = new JButton();
        JPanel productFilters = new JPanel();
        java.awt.Choice sortBy = new java.awt.Choice();
        java.awt.Label sortByLabel = new java.awt.Label();
        JScrollPane productView = new JScrollPane();
        // Variables declaration - do not modify
        JPanel allProducts = new JPanel();
        JMenuBar header = new JMenuBar();
        JMenu staffPortal = new JMenu();
        JMenu reviewExistingOrder = new JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bikes Ltd.");

        orderNav.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        selectWheels.setText("Select Wheels");
        selectWheels.addActionListener(this::selectWheelsActionPerformed);

        selectFrameSets.setText("Select Frame-Sets");

        selectHandlebars.setText("Select Handlebars");

        viewOrder.setText("View Order");

        javax.swing.GroupLayout orderNavLayout = new javax.swing.GroupLayout(orderNav);
        orderNav.setLayout(orderNavLayout);
        orderNavLayout.setHorizontalGroup(
                orderNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(orderNavLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(selectWheels, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectFrameSets, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectHandlebars, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderNavLayout.setVerticalGroup(
                orderNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderNavLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(orderNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(selectWheels, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectFrameSets, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectHandlebars, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(viewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        sortByLabel.setText("Sort by:");

        javax.swing.GroupLayout productFiltersLayout = new javax.swing.GroupLayout(productFilters);
        productFilters.setLayout(productFiltersLayout);
        productFiltersLayout.setHorizontalGroup(
                productFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productFiltersLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sortByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        productFiltersLayout.setVerticalGroup(
                productFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sortBy, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(sortByLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        productView.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);


        javax.swing.GroupLayout allProductsLayout = new javax.swing.GroupLayout(allProducts);
        allProducts.setLayout(allProductsLayout);

        GroupLayout.SequentialGroup allProductsSequentialGroup = allProductsLayout.createSequentialGroup().addContainerGap();
        GroupLayout.ParallelGroup allProductsParallelGroup = allProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false);

        for (JPanel productPanel : productPanels) {
            allProductsSequentialGroup.addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
            allProductsSequentialGroup.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
            allProductsParallelGroup.addComponent(productPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        }

        allProductsSequentialGroup.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);

        allProductsLayout.setHorizontalGroup(
                allProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(allProductsSequentialGroup)
        );
        allProductsLayout.setVerticalGroup(
                allProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(allProductsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(allProductsParallelGroup)
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        productView.setViewportView(allProducts);

        javax.swing.GroupLayout productBrowseMainLayout = new javax.swing.GroupLayout(productBrowseMain);
        productBrowseMain.setLayout(productBrowseMainLayout);
        productBrowseMainLayout.setHorizontalGroup(
                productBrowseMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(productBrowseMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(productBrowseMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(orderNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(productFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(productView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap())
        );
        productBrowseMainLayout.setVerticalGroup(
                productBrowseMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(productBrowseMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(orderNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productView, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                .addContainerGap())
        );

        staffPortal.setText("Staff Portal");
        staffPortal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        header.add(staffPortal);

        reviewExistingOrder.setText("Review Existing Order");
        reviewExistingOrder.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        header.add(reviewExistingOrder);

        setJMenuBar(header);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(productBrowseMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(productBrowseMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    // End of variables declaration
}
